
#服务器配置
server:
    port: 8888
    servlet:
        session:
            timeout: 50m
    tomcat:
        uri-encoding: utf-8
        
        
#spring相关配置
spring:
    thymeleaf:
        cache: false
    application:
        name: springboot-demo
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initial-size: 5
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        password: root
        url: jdbc:mysql://localhost:3306/spring_boot?useUnicode=true&&characterEncoding=UTF-8&serverTimezone=UTC
        username: root


#mybatis相关配置
mybatis:
    mapper-locations: classpath:/mybatis/mapper/*.xml
    #config-location:  classpath:/mybatis/config/mybatis-config.xml
    
    
#配置信息
config:
    jwt: 
    # 加密密钥
        secret: iwqjhda8232bjgh432[cicada-smile]
    # token有效时长
        expire: 3600
    # header 名称
        header: token 
#控制台打印sql
logging:
  level:
     com.example.demo.mapper: debug
